routes/web.php
<?php

use App\Http\Controllers\AddressController;
use App\Http\Controllers\CustomerController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/customers/');
});

Route::resource('customers', CustomerController::class);

Route::prefix('customers')->name('customers.')->group(function () {
     /**
     * por ser modo test se realizó de esta manera
     */
    Route::get('/{id}/destroy',  [CustomerController::class, 'destroy'])->name('delete');

    Route::resource('/{customer}/addresses', AddressController::class);

    /**
     * por ser modo test se realizó de esta manera
     */
    Route::get('/{customer}/addresses/{address}/destroy',  [AddressController::class, 'destroy'])->name('addresses.delete');
});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'company_id',
        'name',
    ];

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function address()
    {
        return $this->hasMany(Address::class);
    }

    public static function boot() {
        parent::boot();

        static::deleting(function($customer) {
            $customer->address()->delete();
        });
    }
}

app/Http/Controllers/AddressController.php
<?php

namespace App\Http\Controllers;

use App\Models\Address;
use App\Models\Customer;
use Illuminate\Http\Request;

class AddressController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($customer)
    {

        $customer = Customer::with('company')->findOrFail($customer);
        $address = Address::whereHas('customer', function ($query) use ($customer) {
            $query->where('id', $customer->id);
        })->get();
        return view('customers.address.list', ['address'=>$address, 'customer'=> $customer]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($customer)
    {
        $customer = Customer::with('company')->findOrFail($customer);

        $data = (object)[
            'route'  => route('customers.addresses.store', $customer->id),
            'method' => 'POST',
            'fields' => (object)[
                'address' => '',
            ],
        ];
        return view('customers.address.form', ['data'=> $data, 'customer'=> $customer]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store($customer, Request $request)
    {
        $this->validate($request, [
            'address' => 'required',
        ]);

        Customer::findOrFail($customer)->address()->create($request->all());

        return redirect()->route('customers.addresses.index', $customer);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Address  $address
     * @return \Illuminate\Http\Response
     */
    public function edit($customer, $address)
    {
        $address = Address::with('customer')->where('id', $address)->whereHas('customer', function ($query) use ($customer) {
            $query->where('id', $customer);
        })->firstOrFail();

        $customer = $address->customer;

        $data = (object)[
            'route'  => route('customers.addresses.update', ['customer'=> $customer, 'address'=> $address->id]),
            'method' => 'PUT',
            'customer' => $customer,
            'fields' => $address
        ];
        return view('customers.address.form', ['data'=> $data, 'customer'=> $customer]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Address  $address
     * @return \Illuminate\Http\Response
     */
    public function update($customer, Request $request, $address)
    {
        $this->validate($request, [
            'address'    => 'required',
        ]);

        $address = Address::where('id', $address)->whereHas('customer', function ($query) use ($customer) {
            $query->where('id', $customer);
        })->firstOrFail();
        $address->update($request->all());
        return redirect()->route('customers.addresses.index', $customer);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Address  $address
     * @return \Illuminate\Http\Response
     */
    public function destroy($customer, $address)
    {
        $address = Address::where('id', $address)->whereHas('customer', function ($query) use ($customer) {
            $query->where('id', $customer);
        })->firstOrFail();
        $address->delete();
        return redirect()->route('customers.addresses.index', $customer);
    }
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use App\Models\Customer;
use Illuminate\Http\Request;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customer::with('company')->get();
        return view('customers.list', compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::all();
        $data = (object)[
            'route'  => route('customers.store'),
            'method' => 'POST',
            'companies' => $companies,
            'fields' => (object)[
                'name'       => '',
                'company_id' => '',
            ],
        ];
        return view('customers.form', compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'company_id' => 'required|numeric',
            'name'        => 'required|string|max:100',
        ]);

        Customer::create($request->all());

        return redirect()->route('customers.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function show(Customer $customer)
    {
        //
        return ;

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customer = Customer::findOrFail($id);
        $companies = Company::all();

        $data = (object)[
            'route'  => route('customers.update', $customer->id),
            'method' => 'PUT',
            'companies' => $companies,
            'fields' => $customer
        ];
        return view('customers.form', compact('data'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'company_id' => 'required|numeric',
            'name'    => 'required|string|max:100',
        ]);

        $customer = Customer::findOrFail($id);
        $customer->update($request->all());
        return redirect()->route('customers.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $customer = Customer::findOrFail($id);
        $customer->delete();
        return redirect()->route('customers.index');
    }
}

resources/views/customers/address/form.blade.php
@extends('layouts.app')
@section('content')
<form id="form1" action="{{ $data->route }}" method="POST" enctype="multipart/form-data">

<div class="row">
    <div class="col-md-8 offset-md-2 text-center p-4">
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a name="" id="" class="btn btn-primary" href="{{ route('customers.addresses.index', $customer->id) }}" role="button">Cancelar</a>
    </div>
    <div class="col-md-8 offset-md-2">
        <strong>Empresa: </strong>{{ $customer->company->name }}<br>
        <strong>Cliente: </strong>{{ $customer->name }}
    </div>
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <div class="card-body">
                    @csrf
                    @method($data->method)
                    <div class="mb-3">
                        <label for="address" class="form-label">Dirección</label>
                          <textarea class="form-control" name="address" id="address" rows="3" required>@if (old('address')){{ old('address') }}@else{{ $data->fields->address}}@endif</textarea>
                    </div>


            </div>
        </div>
    </div>
</div>
</form>

@endsection
@section('scripts-footer')
<script>

</script>

@endsection

resources/views/customers/address/list.blade.php
@extends('layouts.app')
@section('content')
<div class="row">

    <div class="col-md-8 offset-md-2 text-center p-4">
        <a class="btn btn-primary" href="{{ route('customers.addresses.create', ['customer'=> $customer]) }}" role="button">Agregar</a>
        <a class="btn btn-primary" href="{{ route('customers.index') }}" role="button">Listado de clientes</a>

    </div>
    <div class="col-md-8 offset-md-2">
        <strong>Empresa: </strong>{{ $customer->company->name }}<br>
        <strong>Cliente: </strong>{{ $customer->name }}
    </div>


    <div class="col-md-8 offset-md-2">
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col" width="10%">#</th>
                            <th scope="col" width="80%">Dirección</th>
                            <th scope="col" width="10%">Acciones</th>
                        </tr>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($address as $item)
                        <tr>
                            <th scope="row">{{ $item->id }}</th>
                            <td>{{ $item->address }}</td>
                            <td>
                                <a class="link" href="{{ route('customers.addresses.edit', ['customer'=> $customer->id, 'address'=> $item->id]) }}">Editar</a>
                                <a class="link" href="{{ route('customers.addresses.delete', ['customer'=> $customer->id, 'address'=> $item->id]) }}">Eliminar</a>
                            </td>
                        </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts-footer')
<script>

</script>

@endsection