routes/web.php
<?php

use App\Http\Controllers\AddressController;
use App\Http\Controllers\CustomerController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/customers/');
});

Route::resource('customers', CustomerController::class);

Route::prefix('customers')->name('customers.')->group(function () {
     /**
     * por ser modo test se realizó de esta manera
     */
    Route::get('/{id}/destroy',  [CustomerController::class, 'destroy'])->name('delete');

    Route::resource('/{customer}/addresses', AddressController::class);

    /**
     * por ser modo test se realizó de esta manera
     */
    Route::get('/{customer}/addresses/{address}/destroy',  [AddressController::class, 'destroy'])->name('addresses.delete');
});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'company_id',
        'name',
    ];

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function address()
    {
        return $this->hasMany(Address::class);
    }

    public static function boot() {
        parent::boot();

        static::deleting(function($customer) {
            $customer->address()->delete();
        });
    }
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use App\Models\Customer;
use Illuminate\Http\Request;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customer::with('company')->get();
        return view('customers.list', compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::all();
        $data = (object)[
            'route'  => route('customers.store'),
            'method' => 'POST',
            'companies' => $companies,
            'fields' => (object)[
                'name'       => '',
                'company_id' => '',
            ],
        ];
        return view('customers.form', compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'company_id' => 'required|numeric',
            'name'        => 'required|string|max:100',
        ]);

        Customer::create($request->all());

        return redirect()->route('customers.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function show(Customer $customer)
    {
        //
        return ;

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customer = Customer::findOrFail($id);
        $companies = Company::all();

        $data = (object)[
            'route'  => route('customers.update', $customer->id),
            'method' => 'PUT',
            'companies' => $companies,
            'fields' => $customer
        ];
        return view('customers.form', compact('data'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'company_id' => 'required|numeric',
            'name'    => 'required|string|max:100',
        ]);

        $customer = Customer::findOrFail($id);
        $customer->update($request->all());
        return redirect()->route('customers.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $customer = Customer::findOrFail($id);
        $customer->delete();
        return redirect()->route('customers.index');
    }
}

resources/views/customers/form.blade.php
@extends('layouts.app')
@section('content')
<form id="form1" action="{{ $data->route }}" method="POST" enctype="multipart/form-data">

<div class="row">
    <div class="col-md-12 text-center p-4">
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a name="" id="" class="btn btn-primary" href="{{ route('customers.index') }}" role="button">Cancelar</a>
    </div>
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <div class="card-body">
                    @csrf
                    @method($data->method)

                    <div class="mb-3">
                        <label for="name" class="form-label">Compañía</label>
                          <label for=""></label>
                          <select class="form-control" name="company_id" id="company_id">
                            <option value="">Seleccione</option>
                            @foreach ($data->companies as $company)
                                <option value="{{ $company->id }}" {{ ((old('company_id') ? old('company_id') : $data->fields->company_id) == $company->id) ? 'selected' : '' }}>{{ $company->name }}</option>
                            @endforeach
                          </select>
                    </div>
                    <div class="mb-3">
                        <label for="name" class="form-label">Nombre</label>
                        <input type="text" class="form-control" id="name" name="name" value="@if (old('name')){{ old('name') }}@else{{ $data->fields->name }}@endif" required>
                    </div>


            </div>
        </div>
    </div>
</div>
</form>

@endsection
@section('scripts-footer')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<script>
    $(document).ready(function () {

        $('#company_id').select2();
    });
</script>

@endsection

resources/views/customers/list.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-md-12 text-center p-4">
        <a class="btn btn-primary" href="{{ route('customers.create') }}" role="button">Agregar</a>
    </div>
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Compañía</th>
                            <th scope="col">Cliente</th>
                            <th scope="col">Direcciones</th>
                            <th scope="col">Acciones</th>
                        </tr>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($customers as $item)
                        <tr>
                            <th scope="row">{{ $item->id }}</th>
                            <td>{{ $item->company->name }}</td>
                            <td>{{ $item->name }}</td>
                            <td>
                                <a class="link" href="{{ route('customers.addresses.index', ['customer'=> $item->id]) }}">Direcciones</a>
                            </td>
                            <td>
                                <a class="link" href="{{ route('customers.edit', $item->id) }}">Editar</a>
                                <a class="link eliminar" href="{{ route('customers.delete', $item->id) }}">Eliminar</a>
                            </td>
                        </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts-footer')
<script>

</script>

@endsection